# Generated by Django 4.0.2 on 2022-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='box_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memes',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
