# Generated by Django 4.0.2 on 2022-02-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_memes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='image',
        ),
    ]
